server:
  port: 9081

spring:
  application:
    name: DEVELOPMENT

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://127.0.0.1:3306/crud_user
    password: postgres1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwtToken:
  secret: sra-secret-key
