version: "3.8"
services:
  db:
    container_name: Crud_User
    image: postgres
    ports:
      - ":5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=crud_user